In [ ]:
import numpy as np
import pandas as pd
from pandas import Series
from pandas import DataFrame

s1= Series( [4.5, 7.2, -5.3, 3.6], index=list("dbac") )
s1


d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

# Reindexado

In [ ]:
#De esta manera, no se reindexan los índices
s2= Series(s1, index=["l", "m", "n", "o"])
s2

l   NaN
m   NaN
n   NaN
o   NaN
dtype: float64

In [ ]:
s1.index= list("lmno")
s1

l    4.5
m    7.2
n   -5.3
o    3.6
dtype: float64

In [ ]:
s1.reindex( ["m","p","n","o","q"], method="ffill")

m    7.2
p    3.6
n   -5.3
o    3.6
q    3.6
dtype: float64

# Cómo alinear los datos

In [ ]:
s1= Series( [4.5, 7.2, -5.3, 3.6], index=list("dbac") )
s2= Series( [0, 7, 1, 2, 3], index=list("dbecf") )

s1+s2

a     NaN
b    14.2
c     5.6
d     4.5
e     NaN
f     NaN
dtype: float64

In [ ]:
s1.add(s2)

a     NaN
b    14.2
c     5.6
d     4.5
e     NaN
f     NaN
dtype: float64

In [ ]:
s1.add(s2, fill_value=0)

a    -5.3
b    14.2
c     5.6
d     4.5
e     1.0
f     3.0
dtype: float64

In [ ]:
frame1= DataFrame(np.arange(12.).reshape((3,4)), columns=list("abcd"))
frame2= DataFrame(np.arange(20.).reshape((4,5)), columns=list("abcde"))

frame1.add(frame2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
# add, sub, div, mul, pow, floordiv
frame1.mul(frame2, fill_value=1)

a     b      c      d     e
0   0.0   1.0    4.0    9.0   4.0
1  20.0  30.0   42.0   56.0   9.0
2  80.0  99.0  120.0  143.0  14.0
3  15.0  16.0   17.0   18.0  19.0

In [ ]:
# radd, rsub, rdiv, rmul, rpow, rfloordiv -> cambia el orden de los operadores
frame1.rsub(frame2, fill_value=0)

a     b     c     d     e
0   0.0   0.0   0.0   0.0   4.0
1   1.0   1.0   1.0   1.0   9.0
2   2.0   2.0   2.0   2.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
frame1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
# Se puede rellenar un reindex también utilizando fill_value
frame1.reindex(columns=frame2.columns, fill_value=1000)

a    b     c     d     e
0  0.0  1.0   2.0   3.0  1000
1  4.0  5.0   6.0   7.0  1000
2  8.0  9.0  10.0  11.0  1000

# Operaciones entre Dataframes/Series

In [ ]:
frame1= DataFrame(np.arange(12.).reshape((3,4)), columns=list("abcd"))
frame2= DataFrame(np.arange(12.).reshape((4,3)), columns=list("bde"), index=["Sinaloa", "Tamaulipas", "Jalisco", "Nayarit"])
s1= frame2.iloc[0]
s2= Series(range(3), index= ["b", "e", "f"])
arr= np.arange(12.).reshape((3,4))
print(arr)
print(arr- arr[0])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]


In [ ]:
display(frame2)
display(s1)
frame2-s1

b     d     e
Sinaloa     0.0   1.0   2.0
Tamaulipas  3.0   4.0   5.0
Jalisco     6.0   7.0   8.0
Nayarit     9.0  10.0  11.0

b    0.0
d    1.0
e    2.0
Name: Sinaloa, dtype: float64

b    d    e
Sinaloa     0.0  0.0  0.0
Tamaulipas  3.0  3.0  3.0
Jalisco     6.0  6.0  6.0
Nayarit     9.0  9.0  9.0

In [ ]:
s2= np.arange(3)
display(frame2)
display(s2)
frame2+ s2

b     d     e
Sinaloa     0.0   1.0   2.0
Tamaulipas  3.0   4.0   5.0
Jalisco     6.0   7.0   8.0
Nayarit     9.0  10.0  11.0

array([0, 1, 2])

b     d     e
Sinaloa     0.0   2.0   4.0
Tamaulipas  3.0   5.0   7.0
Jalisco     6.0   8.0  10.0
Nayarit     9.0  11.0  13.0

In [ ]:
## Restar una columna
s3= frame2["d"]
s3

Sinaloa        1.0
Tamaulipas     4.0
Jalisco        7.0
Nayarit       10.0
Name: d, dtype: float64

In [ ]:
display(frame2)
display(s3)
frame2- s3

b     d     e
Sinaloa     0.0   1.0   2.0
Tamaulipas  3.0   4.0   5.0
Jalisco     6.0   7.0   8.0
Nayarit     9.0  10.0  11.0

Sinaloa        1.0
Tamaulipas     4.0
Jalisco        7.0
Nayarit       10.0
Name: d, dtype: float64

Jalisco  Nayarit  Sinaloa  Tamaulipas   b   d   e
Sinaloa         NaN      NaN      NaN         NaN NaN NaN NaN
Tamaulipas      NaN      NaN      NaN         NaN NaN NaN NaN
Jalisco         NaN      NaN      NaN         NaN NaN NaN NaN
Nayarit         NaN      NaN      NaN         NaN NaN NaN NaN

In [ ]:
display(frame2)
display(s3)
frame2.sub(s3, axis="index")

b     d     e
Sinaloa     0.0   1.0   2.0
Tamaulipas  3.0   4.0   5.0
Jalisco     6.0   7.0   8.0
Nayarit     9.0  10.0  11.0

Sinaloa        1.0
Tamaulipas     4.0
Jalisco        7.0
Nayarit       10.0
Name: d, dtype: float64

b    d    e
Sinaloa    -1.0  0.0  1.0
Tamaulipas -1.0  0.0  1.0
Jalisco    -1.0  0.0  1.0
Nayarit    -1.0  0.0  1.0

# Funciones y mapeo

In [ ]:
frame3= frame2.rsub(1)
display(frame3)

b    d     e
Sinaloa     1.0  0.0  -1.0
Tamaulipas -2.0 -3.0  -4.0
Jalisco    -5.0 -6.0  -7.0
Nayarit    -8.0 -9.0 -10.0

In [ ]:
np.abs(frame3)

b    d     e
Sinaloa     1.0  0.0   1.0
Tamaulipas  2.0  3.0   4.0
Jalisco     5.0  6.0   7.0
Nayarit     8.0  9.0  10.0

In [ ]:
def f(x):
    return x.max() + x.min()

display(frame3)
frame3.apply(f)

b    d     e
Sinaloa     1.0  0.0  -1.0
Tamaulipas -2.0 -3.0  -4.0
Jalisco    -5.0 -6.0  -7.0
Nayarit    -8.0 -9.0 -10.0

b    -7.0
d    -9.0
e   -11.0
dtype: float64

In [ ]:
frame3.apply(f, axis="columns")

Sinaloa        0.0
Tamaulipas    -6.0
Jalisco      -12.0
Nayarit      -18.0
dtype: float64

In [ ]:
def f2(x):
    return Series([x.min(), x.max(), x.median()], index=["min", "max", "mediana"])
display(frame3)
frame3.apply(f2 )

b    d     e
Sinaloa     1.0  0.0  -1.0
Tamaulipas -2.0 -3.0  -4.0
Jalisco    -5.0 -6.0  -7.0
Nayarit    -8.0 -9.0 -10.0

b    d     e
min     -8.0 -9.0 -10.0
max      1.0  0.0  -1.0
mediana -3.5 -4.5  -5.5

In [ ]:
## Aplicar sobre cada valor
from math import ceil

def f3(x): ## recibe un valor y regresa otro valor
    return ceil(x)

frame3.applymap(f3)

b  d   e
Sinaloa     1  0  -1
Tamaulipas -2 -3  -4
Jalisco    -5 -6  -7
Nayarit    -8 -9 -10